### ISSUE TITLE
Problem with compilation on OpenSUSE

### ISSUE THREAD

**Issue by XuMEPbI4** [alelievr/printf-unit-test#1]
Hello.

On mac checker works fine. Trying to run it on home PC. OS OpenSUSE 15.0 x64.
after runnig make command get a few ot this errors:

> /usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: ft_printf_decimal.o: relocation R_X86_64_32 for «.rodata» can't be used during creating shared object; recompile with -fPIC

I have the ru locale, so this is my translation. As i can see in a Makefile, -fPIC parameter is used during complication. So what is the problem and how i can fix this?

**Comment by alelievr** [comment]
Hi,

This error may happens because i'm extracting the objects files from the static library (.a) you create with the makefile in your ft_printf and it is not supported to link a shared library (.so) with objects files that have not been compiled using -fPIC option.

You can try adding the -FPIC option in your makefile rule to compile you objects.

**Comment by XuMEPbI4** [comment]
Thx I'll try it at home.
Anyway big thanks to you for checker.

**Comment by XuMEPbI4** [comment]
OK, make works without errors, thx
